from django.db import models

class PatientData(models.Model):
    id_number = models.CharField(max_length=50, verbose_name="#ID")
    name = models.CharField(max_length=255)
    date_of_birth = models.DateField(null=True, blank=True)
    gender = models.CharField(max_length=50)
    sz_onset_age = models.CharField(max_length=50, verbose_name="sz onset age (mo)")
    sz_semiology = models.CharField(max_length=255, blank=True, null=True)

    focal = models.BooleanField(default=False)
    gtc = models.BooleanField(default=False)
    tonic = models.BooleanField(default=False)
    clonic = models.BooleanField(default=False)
    tonic_clonic = models.BooleanField(default=False)
    myoclonic = models.BooleanField(default=False)
    typical_absence = models.BooleanField(default=False)
    atypical_absence = models.BooleanField(default=False)
    iterictal_eeg = models.BooleanField(default=False)
    seizure_inducing_factors = models.TextField(blank=True, null=True)
    intelectual_disability = models.BooleanField(default=False)
    global_devolopmental_delay = models.BooleanField(default=False)
    speech_delay = models.BooleanField(default=False)
    behavioral_issues = models.BooleanField(default=False)
    prenatal_history = models.TextField(blank=True, null=True)
    familial_history = models.TextField(blank=True, null=True)
    developmental_encephalopathy = models.BooleanField(default=False)
    epileptic_encephalopathy = models.BooleanField(default=False)
    progressive_microcephaly = models.BooleanField(default=False)
    congenital_microcephaly = models.BooleanField(default=False)
    focal_brain_malformation = models.BooleanField(default=False)
    multifocal_brain_malformation = models.BooleanField(default=False)
    symmetric_polymicrogyria = models.BooleanField(default=False)
    asymmetric_polymicrogyria = models.BooleanField(default=False)
    holoprosencephaly = models.BooleanField(default=False)
    periventricular_heterotopia = models.BooleanField(default=False)
    tuberous_sclerosis = models.BooleanField(default=False)
    simple_febrile_seizure = models.BooleanField(default=False)
    complex_febrile_seizure = models.BooleanField(default=False)
    vaccine_associated = models.BooleanField(default=False)
    developmental_regression = models.BooleanField(default=False)
    motor_delay = models.BooleanField(default=False)
    generalized_hypotonia = models.BooleanField(default=False)
    infantile_axial_hypotonia = models.BooleanField(default=False)
    neck_muscle_weakness = models.BooleanField(default=False)
    spasticity = models.BooleanField(default=False)
    benign_neonatal_seizure = models.BooleanField(default=False)
    pyridoxin_dependent_epilepsy = models.BooleanField(default=False)
    nocturnal_frontal_lobe_epilepsy = models.BooleanField(default=False)
    pnp_oxsidase_deficiency = models.BooleanField(default=False)
    familial_infantile_convulsions = models.BooleanField(default=False)
    dravet_syndrome = models.BooleanField(default=False)
    glut1_deficiency = models.BooleanField(default=False)
    fcd_type_1_2 = models.BooleanField(default=False)
    eies = models.BooleanField(default=False)
    eme = models.BooleanField(default=False)
    eimfs = models.BooleanField(default=False)
    eoee = models.BooleanField(default=False)
    is_infantile_spasms = models.BooleanField(default=False)
    west_syndrome = models.BooleanField(default=False)
    ohtahara_syndrome = models.BooleanField(default=False)
    doose_syndrome = models.BooleanField(default=False)
    lgs = models.BooleanField(default=False)
    emas = models.BooleanField(default=False)
    lks = models.BooleanField(default=False)
    gge = models.BooleanField(default=False)
    cae = models.BooleanField(default=False)
    jae = models.BooleanField(default=False)
    jme = models.BooleanField(default=False)
    tle = models.BooleanField(default=False)
    lafora_rett_syndrome = models.BooleanField(default=False)
    gelastic_epilepsy = models.BooleanField(default=False)
    sturge_weber_syndrome = models.BooleanField(default=False)
    viral_encephalitis = models.BooleanField(default=False)
    cerebral_folate_deficiency = models.BooleanField(default=False)
    limbic_encephalitis = models.BooleanField(default=False)
    dee_swas = models.BooleanField(default=False)
    ee_swas = models.BooleanField(default=False)
    behavioral_arrest = models.BooleanField(default=False)
    negative_myoclonus = models.BooleanField(default=False)
    absence = models.BooleanField(default=False)
    atonic_seizure = models.BooleanField(default=False)
    atypical_absence_2 = models.BooleanField(default=False)
    generalized_myoclonic_seizures = models.BooleanField(default=False)
    myoclonic_absence = models.BooleanField(default=False)
    non_convulsive_status_epilepticus = models.BooleanField(default=False)
    convulsive_status_epilepticus = models.BooleanField(default=False)
    gefs_plus = models.BooleanField(default=False)
    dee = models.BooleanField(default=False)
    hs_hyperthermia_sensitivity = models.BooleanField(default=False)
    cse = models.BooleanField(default=False)
    gms = models.BooleanField(default=False)
    mae = models.BooleanField(default=False)
    coee = models.BooleanField(default=False)
    ftle = models.BooleanField(default=False)
    bfis = models.BooleanField(default=False)
    bfns = models.BooleanField(default=False)
    gepd = models.BooleanField(default=False)
    subcortical_heterotopia = models.BooleanField(default=False)
    pontocerebellar_hypoplasia = models.BooleanField(default=False)
    white_matter_leukodystrophy = models.BooleanField(default=False)
    lissencephaly = models.BooleanField(default=False)

    # Treatment fields (AEDs)
    ets = models.BooleanField(default=False)
    cbz = models.BooleanField(default=False)
    vpa = models.BooleanField(default=False)
    lev = models.BooleanField(default=False)
    tpm = models.BooleanField(default=False)
    clb = models.BooleanField(default=False)
    zns = models.BooleanField(default=False)
    lcm = models.BooleanField(default=False)
    lmt = models.BooleanField(default=False)
    phenytoin = models.BooleanField(default=False)
    vgb = models.BooleanField(default=False)
    pb = models.BooleanField(default=False)
    stp = models.BooleanField(default=False)
    cbd = models.BooleanField(default=False)
    fen = models.BooleanField(default=False)
    rfn = models.BooleanField(default=False)
    per = models.BooleanField(default=False)

    # Other treatments
    intravenous_steroid_pulse = models.BooleanField(default=False)
    hydrocortisone = models.BooleanField(default=False)
    dexamethasone = models.BooleanField(default=False)
    ketogenic_diet = models.BooleanField(default=False)
    ivig = models.BooleanField(default=False)

    # EEGs
    interictal_eeg_final = models.TextField(blank=True, null=True)
    ictal_eeg = models.TextField(blank=True, null=True)
    postictal_eeg = models.TextField(blank=True, null=True)

    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.name} ({self.id_number})"
